# h2 database configuration --testing
spring.datasource.url=jdbc:h2:file:C:/Users/R E V O/Desktop/CourseApi/CourseTestDb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

#For browse
spring.h2.console.path=/h2-console

#username and password for h2 database
spring.datasource.username=sa
spring.datasource.password=root123